void triInsertion(int *array, int size);
void triFusion(int *array, int size);
void triRapidePivotArbitraire(int *array, int start, int end);
void triRapidePivotAleatoire(int *array, int start, int end);
void triRapidePivotOptimal(int *array, int start, int end);
void triParTas(int *tree, int size);
void tamiser(int *tree, int node, int n);
void sort(int *array);
int comp(const void *elem1, const void *elem2);
void triFusion2(int *array, int size, int *buffer);
