void triInsertion(long *array, long size);
void triFusion(long *array, long size);
void triRapidePivotArbitraire(long *array, long start, long end);
void triRapidePivotAleatoire(long *array, long start, long end);
void triRapidePivotMed3(long *array, long start, long end);
void triRapidePivotOptimal(long *array, long start, long end);
void quickSortIterative(long *array, long l, long h);
void quickSortIterativeArbitraire(long *array, long l, long h);
void quickSortIterativeAleatoire(long *array, long l, long h);
void quickSortIterativeMed3(long *array, long l, long h);
void triParTas(long *tree, long size);
void sort(long *array,long size);
